in:
  type: google_spreadsheets
  auth_method: service_account
  json_keyfile: example/service_account_credentials.json
  spreadsheets_url: https://docs.google.com/spreadsheets/d/1Cxz-LudQuhRAGZL8mBoHs6mRnpjODpyF4Rwc5UYoV1E/edit#gid=0
  worksheet_title: UNFORMATTED VALUE
  start_row: 2
  default_timezone: Asia/Tokyo
  null_string: '\N'
  default_typecast: strict
  value_render_option: UNFORMATTED_VALUE
  columns:
    - {name: _c1, type: long}
out:
  type: stdout
