in:
  type: google_spreadsheets
  auth_method: authorized_user
  json_keyfile: example/authorized_user_credentials.json
  spreadsheets_url: https://docs.google.com/spreadsheets/d/1Cxz-LudQuhRAGZL8mBoHs6mRnpjODpyF4Rwc5UYoV1E/edit#gid=0
  worksheet_title: Large Data
  start_row: 2
  default_timezone: Asia/Tokyo
  null_string: '\N'
  default_typecast: strict
  columns:
    - {name: _c1, type: boolean}
    - {name: _c2, type: string}
    - {name: _c3, type: long}
    - {name: _c4, type: double}
    - {name: _c5, type: timestamp, format: '%Y-%m-%d %H:%M:%S.%N'}
    - {name: _c6, type: timestamp, format: '%Y-%m-%d'}
out:
  type: stdout
