in:
  type: googlespreadsheet
  auth_method: refresh_token
  account: 'account'
  json_keyfile: 'example/refresh_token.json'
  spreadsheet_key: spreadsheet_key
  worksheet_title: worksheet_title
  start_row: 2
  start_column: 1
  end_row: 6
  columns:
    - {name: first,  type: string}
    - {name: second, type: double}
    - {name: third,  type: long}
    - {name: fourth, type: timestamp}
    - {name: fifth,  type: json}
    - {name: sixth,  type: boolean}
out:
  type: stdout
